github:[TJRoger]
patreon:TJRoger
open_collective:TJRoger
ko_fi:TJRoger
tidelift:npm/node-dota2-spectator
community_bridge:TJRoger
liberapay:TJRoger
issuehunt:TJRoger
otechie:TJRoger
custom: ["https://paypal.me/rgrl", paypal.me/rgrl]
