# These are supported funding model platforms

github:[TJRoger] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon:TJRoger # Replace with a single Patreon username
open_collective:TJRoger # Replace with a single Open Collective username
ko_fi:TJRoger # Replace with a single Ko-fi username
tidelift:TJRoger # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge:TJRoger # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay:TJRoger # Replace with a single Liberapay username
issuehunt:TJRoger # Replace with a single IssueHunt username
otechie:TJRoger # Replace with a single Otechie username
custom: ['https://paypal.me/rgrl'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
